icons:
- name: button_ok
  title: Done
  shortcut: D
- name: ksmiletris
  title: Feeling good
  shortcut: F
- name: idea
  title: My Own
  shortcut: M
- name: desktop_new
  title: Task
  shortcut: T
- name: stop
  title: Subtle Point
  shortcut: P
- name: korn
  title: Book
  shortcut: B
- name: Mail
  title: Website
  shortcut: W
- name: wizard
  title: Source
  shortcut: S
- name: penguin
  title: Software Project
  shortcut: ''
- name: male1
  title: Personality
  shortcut: Y
- name: help
  title: help
  shortcut: ''
- name: yes
  title: yes
  shortcut: ''
- name: messagebox_warning
  title: messagebox_warning
  shortcut: ''
- name: stop-sign
  title: stop-sign
  shortcut: ''
- name: closed
  title: closed
  shortcut: ''
- name: info
  title: info
  shortcut: ''
- name: button_cancel
  title: button_cancel
  shortcut: ''
- name: full-1
  title: full-1
  shortcut: ''
- name: full-2
  title: full-2
  shortcut: ''
- name: full-3
  title: full-3
  shortcut: ''
- name: full-4
  title: full-4
  shortcut: ''
- name: full-5
  title: full-5
  shortcut: ''
- name: full-6
  title: full-6
  shortcut: ''
- name: full-7
  title: full-7
  shortcut: ''
- name: full-8
  title: full-8
  shortcut: ''
- name: full-9
  title: full-9
  shortcut: ''
- name: full-0
  title: full-0
  shortcut: ''
- name: prepare
  title: prepare
  shortcut: ''
- name: go
  title: go
  shortcut: ''
- name: back
  title: back
  shortcut: ''
- name: forward
  title: forward
  shortcut: ''
- name: up
  title: up
  shortcut: ''
- name: down
  title: down
  shortcut: ''
- name: attach
  title: attach
  shortcut: ''
- name: smiley-angry
  title: smiley-angry
  shortcut: ''
- name: smiley-neutral
  title: smiley-neutral
  shortcut: ''
- name: smiley-oh
  title: smiley-oh
  shortcut: ''
- name: smily_bad
  title: smily_bad
  shortcut: ''
- name: clanbomber
  title: clanbomber
  shortcut: ''
- name: gohome
  title: gohome
  shortcut: ''
- name: folder
  title: folder
  shortcut: ''
- name: kmail
  title: kmail
  shortcut: ''
- name: list
  title: list
  shortcut: ''
- name: edit
  title: edit
  shortcut: ''
- name: kaddressbook
  title: kaddressbook
  shortcut: ''
- name: knotify
  title: knotify
  shortcut: ''
- name: password
  title: password
  shortcut: ''
- name: pencil
  title: pencil
  shortcut: ''
- name: xmag
  title: xmag
  shortcut: ''
- name: bell
  title: bell
  shortcut: ''
- name: bookmark
  title: bookmark
  shortcut: ''
- name: licq
  title: licq
  shortcut: ''
- name: freemind_butterfly
  title: freemind_butterfly
  shortcut: ''
- name: broken-line
  title: broken-line
  shortcut: ''
- name: calendar
  title: calendar
  shortcut: ''
- name: clock
  title: clock
  shortcut: ''
- name: hourglass
  title: hourglass
  shortcut: ''
- name: launch
  title: launch
  shortcut: ''
- name: flag-black
  title: flag-black
  shortcut: ''
- name: flag-blue
  title: flag-blue
  shortcut: ''
- name: flag-green
  title: flag-green
  shortcut: ''
- name: flag-orange
  title: flag-orange
  shortcut: ''
- name: flag-pink
  title: flag-pink
  shortcut: ''
- name: flag-yellow
  title: flag-yellow
  shortcut: ''
- name: flag
  title: flag
  shortcut: ''
- name: family
  title: family
  shortcut: ''
- name: fema
  title: fema
  shortcut: ''
- name: female1
  title: female1
  shortcut: ''
- name: female2
  title: female2
  shortcut: ''
- name: group
  title: group
  shortcut: ''
- name: male2
  title: male2
  shortcut: ''
mapbackcolor: '#FFFFFF'
notebackcolor: '#FFFFFF'
nodestyles:
- title: Good
  refnode:
    text: Sample
    created: 06/18/2016 05:54:28
    modified: 06/18/2016 06:02:55
    fontName: Calibri
    fontSize: 11
    backColor: '#C6EFCE'
    color: '#006100'
- title: Bad
  refnode:
    text: Sample
    created: 06/18/2016 05:54:44
    modified: 06/18/2016 06:02:55
    fontName: Calibri
    fontSize: 11
    backColor: '#FFC7CE'
    color: '#9C0006'
- title: Neutral
  refnode:
    text: Sample
    created: 06/18/2016 05:54:54
    modified: 06/18/2016 06:02:55
    fontName: Calibri
    fontSize: 11
    backColor: '#FFEB9C'
    color: '#9C6500'
- title: Explanatory Note
  refnode:
    text: Sample
    created: 06/18/2016 05:55:07
    modified: 06/18/2016 06:02:55
    italic: True
    fontSize: 9
    color: '#666666'
- title: Warning Text
  refnode:
    text: Sample
    created: 06/18/2016 05:55:15
    modified: 06/18/2016 06:02:55
    color: '#FF0000'
- title: Emphasize
  refnode:
    text: Sample
    created: 06/18/2016 05:55:34
    modified: 06/18/2016 06:02:55
    shape: Bubble
    lineWidth: 2
    lineColor: '#00B050'
